spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/project
    username: root
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: Heshamahmed2003.ha@gmail.com
    password: qwth puyx jcgf jjlt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: your_secret_key_here
  expiration: 86400000 # Token expiration time in milliseconds (24 hours)
